config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'

  devise_for :users, controllers: { invitations: 'users/invitations' }

  resources :users,
            only: [:index, :create, :update, :destroy],
            defaults: { format: :json } do
    member do
      get 'approval_requests'
      get 'available_vacations'
      get 'invite'
      get 'requested_vacations'
      get 'vacation_approvals'
    end
  end

  resources :teams,
            only: [:index, :create, :update, :destroy],
            defaults: { format: :json } do
    member do
      get 'members'
      get 'vacations'
    end
  end

  resources :team_roles,
            only: [:index, :create, :destroy],
            defaults: { format: :json } do
  end

  resources :holidays,
            only: [:index, :create, :update, :destroy],
            defaults: { format: :json }

  resources :available_vacations,
            only: [:index],
            defaults: { format: :json }

  resources :vacation_requests,
            only: [:index, :show, :create, :update],
            defaults: { format: :json } do
    member do
      get 'approvers'
      get 'cancel'
      get 'finish'
      get 'start'
    end
  end

  resources :approval_requests,
            only: [:index],
            defaults: { format: :json } do
    member do
      get 'accept'
      get 'decline'
    end
  end

  resources :reports,
            only: [:index, :show, :create, :update, :destroy],
            defaults: { format: :json }
  
  get 'download_reports' => 'reports#download_reports'
  get 'download_report' => 'reports#download_report'
            
end

app/models/report.rb
class Report < ActiveRecord::Base

  belongs_to :user

  scope :this_months_report, -> do
    where("created_at >= ? AND created_at <= ?", Time.zone.now.beginning_of_month, Time.zone.now.end_of_month)
  end

  # def self.this_months_report
  #   where("created_at >= ? AND created_at <= ?", Time.zone.now.beginning_of_month, Time.zone.now.end_of_month)
  # end
  #validates :body, length: { minimum: 20}
  #csv
  def self.to_csv(user_id=nil)
  	reports = user_id.nil? ? this_months_report : where(user_id: user_id).this_months_report
  	reports = reports.to_a
  	#reports = where(user_id: user_id).to_a
  	CSV.generate do |csv|
  		# raise column_names.inspect
  		csv << column_names
  		reports.each do |report|
  		  csv << report.attributes.values_at(*column_names)
  		end
  	end
  end

  def self.test
    p 'test passed, dude'
  end

end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController

  require "csv"

  before_action :authenticate_user!
  before_action :set_report, only: [:show, :edit, :update, :destroy]
  
  def index
     render json: current_user.reports
    #render text: Report.to_csv(current_user.id)
  end

  def download_report
    respond_to do |format|
      format.json { render json: current_user.reports.to_a }
      format.csv { render text: Report.to_csv(current_user.id) }
    end
  end

  def download_reports
    render text: Report.to_csv
  end

  def show
    render json: @report
  end

  def new
    #@report = Report.new
  end

  def edit
  end

  def create
    @report = current_user.reports.new(report_params)

      if @report.save
        render status: :created, json: @report
      else
        render status: :unprocessable_entity,
               json: { errors: @report.errors.full_messages }
      end
      
  end

  def update
      if @report.update(report_params)
        render status: :ok, json: @report
      else
        render status: :unprocessable_entity,
               json: { errors: @report.errors.full_messages }
      end
  end

  def destroy
    @report.destroy
    render json: {}, status: :no_content
  end

  private
    def set_report
      @report = Report.find(params[:id])
    end

    def report_params
      params.require(:report).permit(:body, :user_id)
    end
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/reports/_form.html.haml
= form_for @report do |f|
  - if @report.errors.any?
    #error_explanation
      %h2= "#{pluralize(@report.errors.count, "error")} prohibited this report from being saved:"
      %ul
        - @report.errors.full_messages.each do |msg|
          %li= msg

  .actions
    = f.submit 'Save'

app/views/reports/edit.html.haml
%h1 Editing report

= render 'form'

= link_to 'Show', @report
\|
= link_to 'Back', reports_path

app/views/reports/index.html.haml
%h1 Listing reports

%table
  %thead
    %tr
      %th
      %th
      %th

  %tbody
    - @reports.each do |report|
      %tr
        %td= link_to 'Show', report
        %td= link_to 'Edit', edit_report_path(report)
        %td= link_to 'Destroy', report, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Report', new_report_path

app/views/reports/new.html.haml
%h1 New report

= render 'form'

= link_to 'Back', reports_path

app/views/reports/show.html.haml
%p#notice= notice


= link_to 'Edit', edit_report_path(@report)
\|
= link_to 'Back', reports_path